// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYvlWEF4LaPR8vfUR3YcH9POkZqMaJzME',
    appId: '1:177452283443:web:7ab7001530a2488f8a9546',
    messagingSenderId: '177452283443',
    projectId: 'com-app-74457',
    authDomain: 'com-app-74457.firebaseapp.com',
    storageBucket: 'com-app-74457.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8E0VH4vJj4vB4jeJNTey86ruISQpAe9k',
    appId: '1:177452283443:android:e6ad26214765f9c68a9546',
    messagingSenderId: '177452283443',
    projectId: 'com-app-74457',
    storageBucket: 'com-app-74457.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQWqcqKEkD_1NEzyor6YvPjgXbqV-eSwE',
    appId: '1:177452283443:ios:edc8576140fb3c588a9546',
    messagingSenderId: '177452283443',
    projectId: 'com-app-74457',
    storageBucket: 'com-app-74457.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYvlWEF4LaPR8vfUR3YcH9POkZqMaJzME',
    appId: '1:177452283443:web:8e3cb6b0c6af5ab58a9546',
    messagingSenderId: '177452283443',
    projectId: 'com-app-74457',
    authDomain: 'com-app-74457.firebaseapp.com',
    storageBucket: 'com-app-74457.appspot.com',
  );

}